maintainer       "Jean-Baptiste Barth"
maintainer_email "jeanbaptiste.barth@gmail.com"
license          "Apache 2.0"
description      "Installs/Configures virtualbox"
long_description "Installs/Configures Oracle's virualbox 4.0"
version          "0.1"
supports         "debian"
supports         "ubuntu"
