maintainer       "Jean-Baptiste Barth"
maintainer_email "jeanbaptiste.barth@gmail.com"
license          "Apache 2.0"
description      "Installs/Configures sqlite"
long_description "Installs/Configures sqlite 3.7+, needed by rails3/sqlite3 gem"
version          "0.1"
supports         "debian"
supports         "ubuntu"
